name: Terraform Plan (PR)

on:
  pull_request:
    branches: [main]
    paths:
      - "modules/**"
      - "envs/**"

jobs:
  plan:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3

      - name: Terraform Init (Dev)
        run: terraform -chdir=envs/dev init

      - name: Terraform Plan (Dev)
        run: terraform -chdir=envs/dev plan




      - name: Install Conftest
        run: |
          wget https://github.com/open-policy-agent/conftest/releases/latest/download/conftest_0.56.0_Linux_x86_64.tar.gz
          tar xzf conftest_0.56.0_Linux_x86_64.tar.gz
          sudo mv conftest /usr/local/bin/

      - name: Terraform Plan JSON Export
        run: |
          terraform -chdir=envs/dev plan -out=tfplan
          terraform -chdir=envs/dev show -json tfplan > plan.json

      - name: Conftest Policy Check
        run: conftest test plan.json -p policy/
